### ISSUE TITLE
Create hotfix for accuracy display problem

### ISSUE THREAD

**Issue by ghost** [tron90/HHU_ML_DL_WS_2016_17#13]
I have found the reason for the problem with showing accuracy:
Codeline 94
`print("step %d, training accuracy %f"%(i, train_accuracy))`
has to be changed to
`print("step", i, ", training accuracy", train_accuracy)`

But I am not sure how is the git workflow for hotfix, so @RobinThues, @AxXxel001 or @MrEricblau please help to integrate this fix! 

May I ask you to leave a comment with explanation, how we treat hotfixes, many thanks!

**Comment by RobinThues** [comment]
I've tried something and
`print 'step: {0}, training accuracy: {1}'.format(i, train_accuracy)`
works fine for me!
I even see about 12 digits of accuracy now.
