### ISSUE TITLE
Add dir structure and .gitignore

### ISSUE THREAD

**Issue by AxXxel001** [tron90/HHU_ML_DL_WS_2016_17#2]
My suggestion:

- directory 'data' to store the MNIST data set
- directory 'bin' for the actual code

The .gitignore should definitely contain data/*. We dont need several hundreds of MB in the online repo.

We also should add either a shell- or python script to set up the project (download the data set, extract it into data/ and maybe further stuff later)

**Comment by RobinThues** [comment]
Tensorflow got built-in example to download and extract the data direct from within our project, see tensorflow.examples.tutorials.mnist - the downlaoded compressed data is about 50mb in size. ofc it should still be included in the .gitignore
