### ISSUE TITLE
Write a config file to source out the meta parameters of the CNN

### ISSUE THREAD

**Issue by AxXxel001** [tron90/HHU_ML_DL_WS_2016_17#3]
Stuff like number of hidden layers and their actual size should not be hard coded. In this way we could test mutiple configurations and compare the results

**Comment by RobinThues** [comment]
I like this. This way we could also try writing a script that tests multiple configurations for us

**Comment by AxXxel001** [comment]
Exactly! :-)

**Comment by AxXxel001** [comment]
Important: I would suggest, that the config file is just a plain json file. What do you guys think?

**Comment by ghost** [comment]
Great idea guys, feel free to create some according automation.
